export enum ClubCategory {
  "Just talking" = "just talking",
  Business = "business",
  Books = "books",
  Cars = "cars",
  Culture = "culture",
  Education = "education",
  Entertainment = "entertainment",
  Fashion = "fashion",
  Finance = "finance",
  Food = "food",
  Games = "games",
  Health = "health",
  Music = "music",
  Pets = "pets",
  Politics = "politics",
  Science = "science",
  Sports = "sports",
  Technology = "technology",
  Travel = "travel",
  Other = "other",
}
